### ISSUE TITLE
File naming

### ISSUE THREAD

**Issue by KatrinBeyer** [eesd-epfl/Statique_I#1]
All files (tex and figure files) should be renamed including the topic (and excluding the exercise number - which might change in a future version of the booklet)

**Comment by KatrinBeyer** [comment]
Circular tunnel: At the moment only hand-written solution. Should be updated to match the standard style. Also - pressure should be written such that it is negative when pointing downwards (and therefore the resultant P should be positive when pointing upwards, i.e. similar to rectangular tunnel).

**Comment by baptvincens** [comment]
OK, I renamed the figures and solution files to include the name of the exercice and I gave each one a letter so that we don't lose the order.
